name: Build Artifact

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: icepuma/rust-action@master
      with:
        args: |
          cargo build --release
          mkdir release
          cp -r data release
          cp target/release/german-verben release
    - uses: actions/upload-artifact@v2
      with:
        name: rusty-german
        path: release
