name: Build Artifact

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: icepuma/rust-action@master
      with:
        args: |
          cargo build
          mkdir release
          mkdir release/data
          cp target/release/german-verben release/rusty-german
          cp -r data release/data
    - uses: actions/upload-artifact@v2
      with:
        name: rusty-german
        path: release/
