name: Rust Example

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v1
    - uses: icepuma/rust-action@master
      with:
        args: cargo build
    - uses: actions/upload-artifact@v2
      with:
        name: rusty-german
        path: |
          target/release/german-verben
          data/
